<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wizards" nsURI="/ejemplo/metamodel/wizards.ecore" nsPrefix="wizards">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Wizard">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="initialPageReturnButtons pagesReturnButtons atLeastCloseBtn"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="initialPageReturnButtons" value="&#xA;&#x9;&#x9;&#x9;self.initialPage.buttons->forAll(b | not b.oclIsTypeOf(ReturnButton))"/>
      <details key="pagesReturnButtons" value="&#xA;&#x9;&#x9;pages->forAll(p : Page |&#xA;&#x9;&#x9;&#x9;p &lt;> self.initialPage implies p.buttons->one(b | b.oclIsTypeOf(ReturnButton))&#xA;&#x9;&#x9;)"/>
      <details key="atLeastCloseBtn" value="pages->forAll(p | &#xA;&#x9;&#x9;&#x9;(p.buttons->select(b | b.oclIsTypeOf(NavButton))->size()=0 &#xA;&#x9;&#x9;&#x9;and p.buttons->select(b | b.oclIsTypeOf(ReturnButton))->size()=0)&#xA;&#x9;&#x9;&#x9;implies p.buttons->select(b | b.oclIsTypeOf(CloseButton))->size()>0&#xA;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialPage" lowerBound="1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" ordered="false"
        upperBound="-1" eType="#//Page" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="buttonsDifferentLabel notOnlyShowBtns notSelfLoop"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="buttonsDifferentLabel" value="buttons->forAll(&#xA;&#x9;&#x9;&#x9;b1,b2 : Button | b1 &lt;> b2 implies b1.label &lt;> b2.label&#xA;&#x9;&#x9;)"/>
      <details key="notOnlyShowBtns" value="&#xA;&#x9;&#x9;&#x9;buttons->select(b | b.oclIsTypeOf(ShowButton))->size() &lt; buttons->size()"/>
      <details key="notSelfLoop" value="buttons->select(b | &#xA;&#x9;&#x9;&#x9;b.oclIsTypeOf(NavButton))->forAll(b2 | b2.targetPage &lt;> self&#xA;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkbox" eType="#//CheckBox"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buttons" ordered="false"
        upperBound="-1" eType="#//Button" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textFields" upperBound="-1"
        eType="#//TextField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextField" eSuperTypes="#//Field">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="labelSize"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="labelSize" value="(minLength &lt;> null and maxLength &lt;> null) implies&#xA;&#x9;&#x9;(label.size() &lt;= maxLength and label.size() >= minLength)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBox" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelSelected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" abstract="true" eSuperTypes="#//Field">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="labelMaxSize"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="labelMaxSize" value="label.size() &lt;= 10"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPage" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherTargetPage" eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavButton" eSuperTypes="#//Button">
    <eOperations name="navigate" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnButton" eSuperTypes="#//Button">
    <eOperations name="return" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShowButton" eSuperTypes="#//Button">
    <eOperations name="show" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloseButton" eSuperTypes="#//Button">
    <eOperations name="close" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
