/*
 * generated by Xtext 2.28.0
 */
package org.xtext.wizard.mydsl.ui.tests;

import com.google.inject.Injector;
import ex2.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.xtext.wizard.mydsl.MyDsl");
	}

}
