/**
 * generated by Xtext 2.28.0
 */
package org.xtext.wizard.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.wizard.mydsl.services.MyDslGrammarAccess;
import wizard.Button;
import wizard.Checkbox;
import wizard.Page;
import wizard.TextField;
import wizard.Wizard;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final Wizard wizard, @Extension final IFormattableDocument document) {
    EList<Page> _pages = wizard.getPages();
    for (final Page page : _pages) {
      document.<Page>format(page);
    }
  }

  protected void _format(final Page page, @Extension final IFormattableDocument document) {
    EList<TextField> _textfields = page.getTextfields();
    for (final TextField textField : _textfields) {
      document.<TextField>format(textField);
    }
    document.<Checkbox>format(page.getCheckbox());
    EList<Button> _buttons = page.getButtons();
    for (final Button button : _buttons) {
      document.<Button>format(button);
    }
  }

  public void format(final Object page, final IFormattableDocument document) {
    if (page instanceof XtextResource) {
      _format((XtextResource)page, document);
      return;
    } else if (page instanceof Page) {
      _format((Page)page, document);
      return;
    } else if (page instanceof Wizard) {
      _format((Wizard)page, document);
      return;
    } else if (page instanceof EObject) {
      _format((EObject)page, document);
      return;
    } else if (page == null) {
      _format((Void)null, document);
      return;
    } else if (page != null) {
      _format(page, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(page, document).toString());
    }
  }
}
